#:kivy 1.0.9

<MyLabel@Label>:
    font_size: 30
    color: 0, 0, 0, 1

<InlineTxt@TextInput>:
    multiline: False

<Separator@Widget>:
    id: separator
    size_hint_y: None
    height: 6
    thickness: 6
    canvas:
        Color:
            rgb: 0, 0, 0, 1
        Rectangle:
            pos: self.pos[0], separator.center_y
            size: separator.width, self.thickness

<HBox@BoxLayout>:
    orientation: 'horizontal'

<VBox@BoxLayout>:
    orientation: 'vertical'

<SoundrainWin>:
    size: 900, 500
    Popup:
        id: PopId
        title: 'Client ID needed'
        VBox:
            spacing: 15
            Image:
                source: 'soundrainlogo.jpg'
            MyLabel:
                color: 1, 1, 1, 1
                height: 50
                size_hint: 1, None
                text: 'Enter your Soundcloud client ID'
            InlineTxt:
                id: IdTxt
                height: 50
                size_hint: 1, None
            MyLabel:
                color: 1, 1, 1, 1
                height: 50
                size_hint: 1, None
                text: '[url=www.google.com]Help?[/url]'
            Button:
                id: IdBut
                text: 'Ok'
                on_press: root.get_id()
    VBox: # Vertical grid for the whole app
        size: root.width - 20, root.height - 100
        pos: 10, 10
        spacing: 20
        HBox: # Horinzontal grid for url part
            size_hint: 1, 0.1
            spacing: 50
            MyLabel:
                height: 50
                size_hint: 0.1, None
                text: 'URL:'
            InlineTxt:
                id: UrlTxt
                height: 50
                size_hint: 0.7, None
                text: "test"
            Button:
                height: 50
                size_hint: 0.2, None
                text: 'Search'
                on_press: root.search_url()
        Separator: # HRule
        HBox: # Vertical grid split for cover and info
            size_hint: 1, 0.7
            spacing: 30
            Image:
                size_hint: 0.4, 1
                allow_stretch: True 
                source: 'unknownperson.jpg'
            VBox: # Infos
                spacing: 20
                size_hint: 0.6, 1
                # Music title
                MyLabel:
                    height: 50
                    size_hint: 1, None
                    text: 'Title:'
                InlineTxt:
                    height: 50
                    size_hint: 1, None
                # Artist name
                MyLabel:
                    height: 50
                    size_hint: 1, None
                    text: 'Artist:'
                InlineTxt:
                    height: 50
                    size_hint: 1, None
                # Album name
                MyLabel:
                    height: 50
                    size_hint: 1, None
                    text: 'Album:'                    
                InlineTxt:
                    height: 50
                    size_hint: 1, None
                # Genre name
                MyLabel:
                    height: 50
                    size_hint: 1, None
                    text: 'Genre:'
                InlineTxt:
                    height: 50
                    size_hint: 1, None
                MyLabel: # I'm using this (poorly) to adjust positionnement
                    height: 125
                    size_hint: 1, None
                    text: ''
        Separator: # HRule
        Button:
            size_hint_y: 0.3, 0.2
            text: 'Download'
